localFolder: 'localfolder'

waitSecondsOnError: 5

scms:

  - name: git
    path: 'path/to/git'

  - name: hg
    path: 'path/to/hg'

sources:

  - hoster: hoster0
    type: type0
    name: name0

  - hoster: hoster1
    type: type1
    name: name1
    ignoreRepos:
        - ignore0
        - ignore1
