//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScmBackup {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal Resource() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScmBackup.Resource", typeof(Resource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Authentication failed for {0}.
        /// </summary>
        public static string ApiAuthenticationFailed {
            get {
                return ResourceManager.GetString("ApiAuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}: Getting {1}.
        /// </summary>
        public static string ApiGettingUrl {
            get {
                return ResourceManager.GetString("ApiGettingUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to User {0} not found!.
        /// </summary>
        public static string ApiInvalidUsername {
            get {
                return ResourceManager.GetString("ApiInvalidUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Required permissions are missing. Make sure you have set the right scopes!.
        /// </summary>
        public static string ApiMissingPermissions {
            get {
                return ResourceManager.GetString("ApiMissingPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ApiRepositories doesn&apos;t contain any HosterRepositories.
        /// </summary>
        public static string ApiRepositoriesContainsNoHosterRepos {
            get {
                return ResourceManager.GetString("ApiRepositoriesContainsNoHosterRepos", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SCM Backup.
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to http://scm-backup.org/.
        /// </summary>
        public static string AppWebsite {
            get {
                return ResourceManager.GetString("AppWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to AuthName and Password are empty.
        /// </summary>
        public static string AuthNameAndPasswortEmpty {
            get {
                return ResourceManager.GetString("AuthNameAndPasswortEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Only one of AuthName/Password is filled. Make sure you fill both or none!.
        /// </summary>
        public static string AuthNameOrPasswortEmpty {
            get {
                return ResourceManager.GetString("AuthNameOrPasswortEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Backup failed!.
        /// </summary>
        public static string BackupFailed {
            get {
                return ResourceManager.GetString("BackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Sources in the settings file must have unique titles. Title &quot;{0}&quot; appears more than once!.
        /// </summary>
        public static string ConfigSourceDuplicateTitle {
            get {
                return ResourceManager.GetString("ConfigSourceDuplicateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to ConfigSource must not be NULL.
        /// </summary>
        public static string ConfigSourceIsNull {
            get {
                return ResourceManager.GetString("ConfigSourceIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to All sources in the settings file must have a title..
        /// </summary>
        public static string ConfigSourceWithoutTitle {
            get {
                return ResourceManager.GetString("ConfigSourceWithoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The application will close in {0} seconds!.
        /// </summary>
        public static string EndSeconds {
            get {
                return ResourceManager.GetString("EndSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Hoster {0} doesn&apos;t exist.
        /// </summary>
        public static string HosterDoesntExist {
            get {
                return ResourceManager.GetString("HosterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Http Headers: {0}.
        /// </summary>
        public static string HttpHeaders {
            get {
                return ResourceManager.GetString("HttpHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Http Request: {0}.
        /// </summary>
        public static string HttpRequest {
            get {
                return ResourceManager.GetString("HttpRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Http Result: {0}.
        /// </summary>
        public static string HttpResult {
            get {
                return ResourceManager.GetString("HttpResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Local folder is missing!.
        /// </summary>
        public static string LocalFolderMissing {
            get {
                return ResourceManager.GetString("LocalFolderMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to name is empty.
        /// </summary>
        public static string NameEmpty {
            get {
                return ResourceManager.GetString("NameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No source configured!.
        /// </summary>
        public static string NoSourceConfigured {
            get {
                return ResourceManager.GetString("NoSourceConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}: Reading config.
        /// </summary>
        public static string ReadingConfig {
            get {
                return ResourceManager.GetString("ReadingConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}: Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to SCM {0} doesn&apos;t exist.
        /// </summary>
        public static string ScmDoesntExist {
            get {
                return ResourceManager.GetString("ScmDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} was NOT found.
        /// </summary>
        public static string ScmNotOnThisComputer {
            get {
                return ResourceManager.GetString("ScmNotOnThisComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0} was found.
        /// </summary>
        public static string ScmOnThisComputer {
            get {
                return ResourceManager.GetString("ScmOnThisComputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to At least one SCM is missing on this machine!.
        /// </summary>
        public static string ScmValidatorError {
            get {
                return ResourceManager.GetString("ScmValidatorError", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Trying to find SCMs on this machine....
        /// </summary>
        public static string ScmValidatorStarting {
            get {
                return ResourceManager.GetString("ScmValidatorStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to {0}: Starting backup.
        /// </summary>
        public static string StartingBackup {
            get {
                return ResourceManager.GetString("StartingBackup", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t register {0} in the HosterFactory because it doesn&apos;t implement IHoster.
        /// </summary>
        public static string TypeIsNoIHoster {
            get {
                return ResourceManager.GetString("TypeIsNoIHoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to Can&apos;t register {0} in the ScmFactory because it doesn&apos;t implement IScm.
        /// </summary>
        public static string TypeIsNoIScm {
            get {
                return ResourceManager.GetString("TypeIsNoIScm", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to wrong hoster: {0}.
        /// </summary>
        public static string WrongHoster {
            get {
                return ResourceManager.GetString("WrongHoster", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to wrong type: {0}.
        /// </summary>
        public static string WrongType {
            get {
                return ResourceManager.GetString("WrongType", resourceCulture);
            }
        }
    }
}
